version: "3"

tasks:
  default:
    desc: "The default task"
    deps:
      - proto

    cmds:
      - task: build-bin
      - goreman start

  build-bin:
    - go build -o ./cmd/landns/landns ./cmd/landns
    - go build -o ./cmd/landns-agent/landns-agent ./cmd/landns-agent

  run-landns:
    desc: "run landns"
    cmds:
      - go run ./cmd/landns

  run-landns-agent:
    desc: "run landns agent"
    cmds:
      - go run ./cmd/landns-agent

  proto:
    desc: "Generate protobuf"
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --twirp_out=. ./pkg/rpcgen/landns.proto

  query:
    desc: "Query the DHCP Manager"
    cmds:
      - ssh root@192.168.100.101 "dig @127.0.0.1 archlinux.lan A"

  ssh:
    desc: "SSH to the server"
    cmds:
      - ssh root@192.168.100.101
